#!/bin/sh

# La V1 n'expose volontairement que l'état en lecture seule dans LuCI.
# L'activation reste une opération console avec jeton explicite.
uci -q delete luci.otb_mxl_flowctrl_status
uci set luci.otb_mxl_flowctrl_status='command'
uci set luci.otb_mxl_flowctrl_status.name='État du contrôle de flux MxL OTB'
uci set luci.otb_mxl_flowctrl_status.description='Affiche les verrous, le pilote, le LACP et le réglage PAUSE du port mxl_lan5.'
uci set luci.otb_mxl_flowctrl_status.command='/usr/libexec/otb-mxl-flowctrl status'
uci set luci.otb_mxl_flowctrl_status.param='0'
uci set luci.otb_mxl_flowctrl_status.public='0'
uci commit luci
exit 0
