#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

append_listen() {
	procd_append_param command -p "$1"
}

start_service() {
	local enabled docroot

	config_load otb-firmware-mirror
	config_get_bool enabled main enabled 0
	config_get docroot main docroot /srv/otb-firmware-mirror

	[ "$enabled" -eq 1 ] || return 0
	[ -d "$docroot" ] || {
		logger -t otb-firmware-mirror -p err \
			"miroir refuse: docroot absent: $docroot"
		return 1
	}
	find "$docroot" -type f -path '*/stable/manifest.json' -print |
		grep -q . || {
			logger -t otb-firmware-mirror -p err \
				'miroir refuse: aucun manifeste stable'
			return 1
		}

	procd_open_instance
	procd_set_param command /usr/sbin/uhttpd \
		-f -D -S -c /dev/null -N 4 -T 20 -h "$docroot"
	config_list_foreach main listen append_listen
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger otb-firmware-mirror
}
